### ISSUE TITLE
how i get deviceInfo ?

### ISSUE THREAD

**Issue by ricardojlrufino** [tuya/tuya-socket-android-sdk#1]
I can't find this api only 

![image](https://github.com/tuya/tuya-socket-android-sdk/assets/515675/8bd6d650-7df4-4862-afc8-70252351db7b)

**Comment by taojingGino** [comment]
you can use HttpURLConnection to get the result

`String url = "xxxxx";
        String bearerToken = "xxxxx";

        try {
            URL obj = new URL(url);
            HttpURLConnection connection = (HttpURLConnection) obj.openConnection();
            connection.setRequestMethod("GET");
            connection.setRequestProperty("Authorization", "Bearer " + bearerToken);

            int responseCode = connection.getResponseCode();
            System.out.println("Response Code : " + responseCode);

            BufferedReader in = new BufferedReader(new InputStreamReader(connection.getInputStream()));
            String inputLine;
            StringBuffer response = new StringBuffer();

            while ((inputLine = in.readLine()) != null) {
                response.append(inputLine);
            }
            in.close();

            // Print the response
            System.out.println(response.toString());
        } catch (Exception e) {
            e.printStackTrace();
        }`
        
@ricardojlrufino

**Comment by ricardojlrufino** [comment]
Thanks for answering.
My question is what is the url? How can I get it?
I already have the device UID

**Comment by taojingGino** [comment]
https://developer.tuya.com/en/docs/iot/api-request?id=Ka4a8uuo1j4t4#title-1-Endpoints

url is here @ricardojlrufino
